

  // Chart data
  export const bookingsData = [
    { name: "Sun", value: 400 },
    { name: "Mon", value: 600 },
    { name: "Tue", value: 800 },
    { name: "Wed", value: 1200 },
    { name: "Thu", value: 800 },
    { name: "Fri", value: 1000 },
    { name: "Sat", value: 1400 },
  ]

  // Category data
  export const categoryData = [
    { name: "Music", value: 14172, percentage: "25.77%", color: "#f364f3" },
    { name: "Sport", value: 12476, percentage: "22.68%", color: "#2d3a5d" },
    { name: "Fashion", value: 9806, percentage: "17.83%", color: "#e6e6e6" },
    { name: "Art & Design", value: 7661, percentage: "13.93%", color: "#f364f3" },
  ]

  // Art & Design subcategories
  export const artDesignData = [
    { name: "Landscape Architecture and Design", value: 3415, total: 4000 },
    { name: "Futuristic Art and Design", value: 2246, total: 2500 },
    { name: "Mixed Media Masterclass", value: 2000, total: 3200 },
  ]

  // Bookings table data
  export const bookingsTableData = [
    {
      invoiceId: "INV10011",
      date: "2029/02/15",
      time: "10:30 AM",
      name: "Jackson Moore",
      event: "Symphony Under the Stars",
      category: "Music",
      ticketCategory: "Diamond",
      price: "$50",
      qty: 2,
      amount: "$100",
      status: "Confirmed",
      eVoucher: "123456-MUSIC",
    },
    {
      invoiceId: "INV10012",
      date: "2029/02/16",
      time: "03:45 PM",
      name: "Alicia Smithson",
      event: "Runway Revolution 2024",
      category: "Fashion",
      ticketCategory: "Platinum",
      price: "$120",
      qty: 1,
      amount: "$120",
      status: "Pending",
      eVoucher: "-",
    },
    {
      invoiceId: "INV10013",
      date: "2029/02/17",
      time: "01:15 PM",
      name: "Natalie Johnson",
      event: "Global Wellness Summit",
      category: "Beauty & Wellness",
      ticketCategory: "CAT 1",
      price: "$80",
      qty: 3,
      amount: "$240",
      status: "Confirmed",
      eVoucher: "769101-WELLNESS",
    },
    {
      invoiceId: "INV10014",
      date: "2029/02/18",
      time: "09:00 AM",
      name: "Patrick Cooper",
      event: "Champions League Screening Night",
      category: "Sport",
      ticketCategory: "CAT 3",
      price: "$30",
      qty: 4,
      amount: "$120",
      status: "Cancelled",
      eVoucher: "-",
    },
    {
      invoiceId: "INV10015",
      date: "2029/02/18",
      time: "05:30 PM",
      name: "Gilda Ramos",
      event: "Artistry Unveiled: Modern Art Expo",
      category: "Art & Design",
      ticketCategory: "Silver",
      price: "$25",
      qty: 2,
      amount: "$50",
      status: "Confirmed",
      eVoucher: "202324-ART",
    },
    {
      invoiceId: "INV10016",
      date: "2029/02/19",
      time: "12:00 PM",
      name: "Clara Simmons",
      event: "Tech Future Expo",
      category: "Technology",
      ticketCategory: "CAT 2",
      price: "$75",
      qty: 2,
      amount: "$150",
      status: "Confirmed",
      eVoucher: "564738-TECH",
    },
    {
      invoiceId: "INV10017",
      date: "2029/02/20",
      time: "02:30 PM",
      name: "Daniel White",
      event: "Culinary Delights Festival",
      category: "Food & Culinary",
      ticketCategory: "Gold",
      price: "$60",
      qty: 1,
      amount: "$60",
      status: "Cancelled",
      eVoucher: "928374-CULINARY",
    },
    {
      invoiceId: "INV10018",
      date: "2029/02/21",
      time: "06:00 PM",
      name: "Natalie Johnson",
      event: "Echo Beats Festival",
      category: "Music",
      ticketCategory: "Platinum",
      price: "$70",
      qty: 3,
      amount: "$210",
      status: "Pending",
      eVoucher: "-",
    },
  ]